name: Test CI
on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master
jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache node modules
      uses: c-hive/gha-npm-cache@v1
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm run coverage
    - name: Generate coverage report
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}